### ISSUE TITLE
apt build-dep does not install Python headers

### ISSUE THREAD

**Issue by srevinsaju** [sugarlabs/sugar-datastore#22]
`sudo apt build-dep sugar-datastore` does not install `python3-dev` which would provide Python3 Headers.

Tested on 
- Debian Buster
- Ubuntu 18.04 Bionic
- Ubuntu (latest)

**Comment by quozl** [comment]
Is fixed downstream already;

* https://packages.debian.org/source/sid/sugar-datastore
* https://packages.debian.org/source/bullseye/sugar-datastore

Can close.

**Comment by srevinsaju** [comment]
Does fixing it on packages.debian also fix it for Ubuntu? I am very new to the `apt` philosophy. Thanks for the quick fix!!

**Comment by quozl** [comment]
I didn't fix it.  Someone else working for Debian project already fixed it.  Evidence of fix is that `python3-dev` is listed in the build dependencies, at the two links I gave.  It's not something we control in the upstream project.  Although @shaansubbaiah is working on a project to improve Debian for us, the problem you describe, which is since solved, isn't something we can fix in the sugar-datastore source repository.

**Comment by chimosky** [comment]
Closing as it's been fixed downstream.

**Comment by srevinsaju** [comment]
Thanks for the info @quozl
